server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/heima?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: hoteladminservice
  rabbitmq:
    host: 192.168.10.100
    prot: 5672
    username: itcast
    password: 123321
    virtual-host: /
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务地址
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo